### PR TITLE
patch: Fixed a bug where file diffs for renamed files were not picked up

### PR DESCRIPTION
**Pull request by gbbr**
File diffs containing only renames are ignored.

screen shot 2015-08-26 at 6 19 32 pm

### CODE REVIEW

**Comment by slimsag** [comment]
- Need a test for this functionality.

Otherwise LGTM

**Comment by gbbr** [comment]
Thanks, will follow-up with a test.

**Comment by shurcooL** [comment]
If this works and is ready to merge, perhaps it's better to do than, rather than not merging at all? Since it fixes a real issue. Tests can be added later as an enhancement.

**Comment by shurcooL** [comment]
> Need a test for this functionality.

Created tests for this in #12.

**Pull request merged**
