### PR TITLE
diff: support renamed, updated binary file

### PR DESCRIPTION
**Pull request by stephen**
This commit parses a diff with a renamed, updated binary file and adds a test case for it.

### CODE REVIEW

**Comment by unknwon** [comment]
Thanks for the PR!

I am not the best to review this code but `.DS_Store` definitely shouldn't be committed :)

**Comment by keegancsmith** [comment]
@stephen ping :)

**Comment by stephen** [comment]
Thanks for the reminder. I removed the .DS_Store and rebased to fix conflicts. I tried to match the changes in https://github.com/sourcegraph/go-diff/commit/f935979a5d70d2f3034edc6de94c77be621ce500 in my new diff.

**Comment by stephen** [comment]
Separately, consider adding `.DS_Store` to a .gitignore might be nice.

**Review by keegancsmith — APPROVED** [review]

**Comment by keegancsmith** [comment]
Thanks!

**Pull request merged**
