### PR TITLE
Go mod tidy sourcegraph

### PR DESCRIPTION
**Pull request by eseliger**
This is a campaign run to fulfill the delivery plan https://github.com/sourcegraph/customer/issues/13. 
Over the coming days, I will update more repositories using `go mod tidy`.

### CODE REVIEW

**Comment by eseliger** [comment]
I have unfortunately no idea what the directive is used for :D but I'm happy to close it, as that will also be a good data point for me testing out the roll-out with all sorts of scenarios!
I might end up moving this campaign to k8s.sgdev.org so I might have to reopen this PR, will close again then though

**Comment by dmitshur** [comment]
Setting the Go language version to 1.14 means that language features that are new to 1.14 may be used, and things that were deprecated/removed may not be.

Since there aren't code changes here, the packages in this module would still build successfully with older versions of Go.

It'd be completely reasonable to specify an older version of the Go language if your intention is not to use any newer Go language features.

See issue golang/go#30791 about documenting the `go` directive better so it's easier for module authors to choose a good value for it.

**Comment by keegancsmith** [comment]
Thanks @dmitshur. So this won't affect any modules which depend on go-diff? If so LGTM

**Comment by keegancsmith** [comment]
Next time I will read the link before asking a question. Looks like this does what I expect.

**Comment by eseliger** [comment]
Thanks for jumping in @dmitshur! I am going to close this PR and will recreate it in the coming hours or days, as the new campaign rollout test will originate from our dogfood instance.

**Comment by dmitshur** [comment]
The `go` directive affects only the Go packages in the module it's in.

Based on what you said, setting it to a lower value like `go 1.13` may be a better fit. The module is tidy as long as the `go` directive is present, it doesn't have to be exactly 1.14. That was just the default value.

**Pull request closed without merging**
